jQuery().snaprec("default",{
	text:true,
	images_loop:true,
	window_page:true,
	view_page:false,
	text_as_html:false,
	zoom_cursor_image:{
		src:"/pc/for_app/cur/zoomin.gif",
		cur:"/pc/for_app/cur/zoomin.cur",
		width:32,
		height:32
	},
	restore_cursor_image:{
		src:"/pc/for_app/cur/zoomout.gif",
		cur:"/pc/for_app/cur/zoomout.cur",
		width:32,
		height:32
	},
	move_cursor:"move",
	close_button_image:{
		src:"/pc/for_app/img/window_close.gif",
		hover:"/pc/for_app/img/window_close_hover.gif",
		width:18,
		height:18
	},
	prev_button_image:{
		src:"/pc/for_app/img/window_prev.gif",
		hover:"/pc/for_app/img/window_prev_hover.gif",
		width:20,
		height:40
	},
	next_button_image:{
		src:"/pc/for_app/img/window_next.gif",
		hover:"/pc/for_app/img/window_next_hover.gif",
		width:20,
		height:40
	}
});;